### ISSUE TITLE
Purpose of this Router?

### ISSUE THREAD

**Issue by newlegendmedia** [cdellacqua/svelte-stack-router#6]
I am working on my first Svelte app and have gotten the basics of Svelte Kit and Svelte figured out mostly. I previously used jquery and my own custom router that was a simple SPA router based on the hash change event. I liked that I could use the back arrow and be right back in the state I was in previously because a hash change did not cause a full refresh of the browser page. 

Is this router intended to have some of the type of functionality? Im struggling with the full refresh between "pages" using the SvelteKit router. There are some very nice aspects of the SvelteKit routing and the server side module script load etc, but I am looking at how I might add that more SPA like approach, including using a hash to route to a particular subview or app state.

**Comment by cdellacqua** [comment]
Hi, thanks for the interest!

Quick answer: yes, it's meant to preserve the full state of the "pages" the user opens during navigation and restore it when necessary.

Long answer: I created this library to solve the problem of having to deal with the extra complexity needed to implement state restoration inside all the different pages. [In the demo](https://cdellacqua.github.io/svelte-stack-router/#/) you can see an example of a video tag being completely restored because it's never actually destroyed and recreated, it just gets parked in memory and brought back when the user comes back to the same "page".

**Comment by newlegendmedia** [comment]
Thanks! Im going to play around more with this router soon and hope to use it in the future.
