### ISSUE TITLE
does it support sub routing?

### ISSUE THREAD

**Issue by easyfrog** [cdellacqua/svelte-stack-router#9]
could it support sub routing?

`index.svetle`
```
var routes = {
     '/': Home,
    '/about': About
}

<StackRouter {routes} />
```

and in `About.svelte`

```
var subRoutes = {
     '/test1': Test1,          //  for  /about/test1
     '/test2': Test2          //  for  /about/test2
}

<!-- pages change in About page -->
<StackRouter routes={subRoutes} />
```

**Comment by cdellacqua** [comment]
There can't be more than one StackRouter component rendered in your Svelte app, because it has to interact with your document and the browser history.

You can, however, change the available routes at runtime, for example by creating a store containing all the routes and changing its value, but mind that the change is not reactive, meaning that if you edit or add a route, the StackRouter won't swap the current page component with the newly registered one until a new navigation event occurs (e.g. link click or `push('/somewhere-new')`).
